"use strict";

var crypto = require('crypto')

// Returns a 4-byte integer generated by hashing the mac address with the date and a salt
module.exports = function hashID (macAddress, date) {
    return new Buffer(crypto.createHash('sha256')
                        .update(macAddress + date + Math.random().toString(36).substr(2, 5))
                        .digest())
                .readUInt32LE(0)
}
